# Application Configuration
server:
  port: 8181

# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlinelibrary?serverTimezone=UTC
    username: Karlen
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

# JWT Configuration
security:
  jwt:
    secret: aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=
    access: 3600000 # Access token validity period in milliseconds (1 hour)
    refresh: 2592000000 # Refresh token validity period in milliseconds (30 days)

# SpringDoc Configuration
springdoc:
  override-with-generic-response: false
